### ISSUE TITLE
Image enlarge option for multiple pages

### ISSUE THREAD

**Issue by dichrozona** [Opfer/ButterflyHub#8]
For use on all pages with a detail image display (Gallery, Taxon, Photographer/User, Compare) have "click on image to enlarge" like this page:

http://www.erdiagrams.com/datamodel-forum-idef1x.html

I like how the image "zooms" from its position to full size. Our "full size" would depend on the resolution of the uploaded image.

**Comment by Opfer** [comment]
For this to work with all the images, we need to relocate the rating stars outside the image. I will try to make them work at on the same place, in case this wouldn't work there is no other choice but to locate it outside the image canvas.

**Comment by Opfer** [comment]
It worked!
